# GNU Make project makefile autogenerated by Premake
ifndef config
  config=release32
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),release32)
  OBJDIR     = obj/x32/Release/Test_OpenCL_Bullet3
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/Test_OpenCL_Bullet3_gmake.exe
  DEFINES   += -D_VARIADIC_MAX=10 -DB3_USE_CLEW -DB3_USE_ZLIB
  INCLUDES  += -I../../src/clew -I../../test/TestBullet3OpenCL -I../../test/gtest-1.7.0/include -I../../src
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -msse2 -ffast-math -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -m32 -L/usr/lib32 -L../../bin -L../../lib
  LIBS      += ../../bin/libgtest_gmake.a ../../lib/libBullet3OpenCL_clew_gmake.a ../../bin/libBullet3Common_gmake.a
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../../bin/libgtest_gmake.a ../../lib/libBullet3OpenCL_clew_gmake.a ../../bin/libBullet3Common_gmake.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug32)
  OBJDIR     = obj/x32/Debug/Test_OpenCL_Bullet3
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/Test_OpenCL_Bullet3_gmake_debug.exe
  DEFINES   += -D_DEBUG=1 -D_VARIADIC_MAX=10 -DB3_USE_CLEW -DB3_USE_ZLIB
  INCLUDES  += -I../../src/clew -I../../test/TestBullet3OpenCL -I../../test/gtest-1.7.0/include -I../../src
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -ffast-math -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -m32 -L/usr/lib32 -L../../bin -L../../lib
  LIBS      += ../../bin/libgtest_gmake_debug.a ../../lib/libBullet3OpenCL_clew_gmake_debug.a ../../bin/libBullet3Common_gmake_debug.a
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../../bin/libgtest_gmake_debug.a ../../lib/libBullet3OpenCL_clew_gmake_debug.a ../../bin/libBullet3Common_gmake_debug.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR     = obj/x64/Release/Test_OpenCL_Bullet3
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/Test_OpenCL_Bullet3_gmake_x64_release.exe
  DEFINES   += -D_VARIADIC_MAX=10 -DB3_USE_CLEW -DB3_USE_ZLIB
  INCLUDES  += -I../../src/clew -I../../test/TestBullet3OpenCL -I../../test/gtest-1.7.0/include -I../../src
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -msse2 -ffast-math -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -m64 -L/usr/lib64 -L../../bin -L../../lib
  LIBS      += ../../bin/libgtest_gmake_x64_release.a ../../lib/libBullet3OpenCL_clew_gmake_x64_release.a ../../bin/libBullet3Common_gmake_x64_release.a
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../../bin/libgtest_gmake_x64_release.a ../../lib/libBullet3OpenCL_clew_gmake_x64_release.a ../../bin/libBullet3Common_gmake_x64_release.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR     = obj/x64/Debug/Test_OpenCL_Bullet3
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/Test_OpenCL_Bullet3_gmake_x64_debug.exe
  DEFINES   += -D_DEBUG=1 -D_VARIADIC_MAX=10 -DB3_USE_CLEW -DB3_USE_ZLIB
  INCLUDES  += -I../../src/clew -I../../test/TestBullet3OpenCL -I../../test/gtest-1.7.0/include -I../../src
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -ffast-math -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -m64 -L/usr/lib64 -L../../bin -L../../lib
  LIBS      += ../../bin/libgtest_gmake_x64_debug.a ../../lib/libBullet3OpenCL_clew_gmake_x64_debug.a ../../bin/libBullet3Common_gmake_x64_debug.a
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../../bin/libgtest_gmake_x64_debug.a ../../lib/libBullet3OpenCL_clew_gmake_x64_debug.a ../../bin/libBullet3Common_gmake_x64_debug.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/clew.o \
	$(OBJDIR)/ioapi.o \
	$(OBJDIR)/unzip.o \
	$(OBJDIR)/zip.o \
	$(OBJDIR)/adler32.o \
	$(OBJDIR)/compress.o \
	$(OBJDIR)/crc32.o \
	$(OBJDIR)/deflate.o \
	$(OBJDIR)/gzclose.o \
	$(OBJDIR)/gzlib.o \
	$(OBJDIR)/gzread.o \
	$(OBJDIR)/gzwrite.o \
	$(OBJDIR)/infback.o \
	$(OBJDIR)/inffast.o \
	$(OBJDIR)/inflate.o \
	$(OBJDIR)/inftrees.o \
	$(OBJDIR)/trees.o \
	$(OBJDIR)/uncompr.o \
	$(OBJDIR)/zutil.o \
	$(OBJDIR)/main.o \
	$(OBJDIR)/testInitOpenCL.o \
	$(OBJDIR)/testCompileBullet3BroadphaseKernels.o \
	$(OBJDIR)/testCompileBullet3IntegrateUpdateAabbKernels.o \
	$(OBJDIR)/testCompileBullet3JacobiContactSolverKernels.o \
	$(OBJDIR)/testCompileBullet3NarrowphaseKernels.o \
	$(OBJDIR)/testCompileBullet3PgsContactSolverKernels.o \
	$(OBJDIR)/testCompileBullet3PgsJointSolverKernels.o \
	$(OBJDIR)/testCompileBullet3RaycastKernels.o \
	$(OBJDIR)/testExecuteBullet3NarrowphaseKernels.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking Test_OpenCL_Bullet3
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning Test_OpenCL_Bullet3
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/clew.o: ../../src/clew/clew.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ioapi.o: ../../btgui/minizip/ioapi.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/unzip.o: ../../btgui/minizip/unzip.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/zip.o: ../../btgui/minizip/zip.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/adler32.o: ../../btgui/zlib/adler32.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/compress.o: ../../btgui/zlib/compress.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/crc32.o: ../../btgui/zlib/crc32.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/deflate.o: ../../btgui/zlib/deflate.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/gzclose.o: ../../btgui/zlib/gzclose.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/gzlib.o: ../../btgui/zlib/gzlib.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/gzread.o: ../../btgui/zlib/gzread.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/gzwrite.o: ../../btgui/zlib/gzwrite.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/infback.o: ../../btgui/zlib/infback.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/inffast.o: ../../btgui/zlib/inffast.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/inflate.o: ../../btgui/zlib/inflate.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/inftrees.o: ../../btgui/zlib/inftrees.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/trees.o: ../../btgui/zlib/trees.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/uncompr.o: ../../btgui/zlib/uncompr.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/zutil.o: ../../btgui/zlib/zutil.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/main.o: ../../test/TestBullet3OpenCL/main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/testInitOpenCL.o: ../../test/OpenCL/BasicInitialize/testInitOpenCL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/testCompileBullet3BroadphaseKernels.o: ../../test/OpenCL/AllBullet3Kernels/testCompileBullet3BroadphaseKernels.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/testCompileBullet3IntegrateUpdateAabbKernels.o: ../../test/OpenCL/AllBullet3Kernels/testCompileBullet3IntegrateUpdateAabbKernels.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/testCompileBullet3JacobiContactSolverKernels.o: ../../test/OpenCL/AllBullet3Kernels/testCompileBullet3JacobiContactSolverKernels.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/testCompileBullet3NarrowphaseKernels.o: ../../test/OpenCL/AllBullet3Kernels/testCompileBullet3NarrowphaseKernels.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/testCompileBullet3PgsContactSolverKernels.o: ../../test/OpenCL/AllBullet3Kernels/testCompileBullet3PgsContactSolverKernels.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/testCompileBullet3PgsJointSolverKernels.o: ../../test/OpenCL/AllBullet3Kernels/testCompileBullet3PgsJointSolverKernels.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/testCompileBullet3RaycastKernels.o: ../../test/OpenCL/AllBullet3Kernels/testCompileBullet3RaycastKernels.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/testExecuteBullet3NarrowphaseKernels.o: ../../test/OpenCL/AllBullet3Kernels/testExecuteBullet3NarrowphaseKernels.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
